---
repos:
-   repo: https://github.com/rcmdnk/pyproject-pre-commit
    rev: v0.1.5
    hooks:
    - id: black
    - id: isort
    - id: mypy
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/pylint
    rev: v3.1.0
    hooks:
    - id: pylint
      stages: [commit]
      name: pylint
      entry: pylint
      language: python
      additional_dependencies:
        - rocrate
        - bagit
        - slugify
        - pytest
        - pandas
        - backoff
        - pydantic
        - ldap3
        - passpy
        - pydantic_settings
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      stages: [pre-push]
      language: python
      additional_dependencies:
        - pytest
      entry: pytest -v tests
      types: [python]
      pass_filenames: false
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
    -   id: python-safety-dependencies-check
-   repo: local
    hooks:
     -   id: wily
         stages: [pre-push]
         name: wily
         entry: wily diff
         verbose: true
         language: python
         additional_dependencies: [wily]